[project]
name="cpp_extension"
requires-python=">=3.4"
readme="README.md"
dependencies=['torch']

version="0.0.1"

[project.urls]
repository="https://github.com/pytorch/extension-cpp"

[build-system]
requires = ["meson-python", "ninja", "torch"]
build-backend = 'mesonpy'


